### ISSUE TITLE
 [ checklist ] 매물 정보 수정 API

### ISSUE THREAD

**Issue by Yeonseo-Jo** [GO-SOPT-GROUP5/ohouse-client#32]
// 제목 → [ 페이지명 ] 내용
## ✅ To Dos
- [ ] 모달 창 정보 수정 : 주소 & 동 & 계약형태 PATCH
- [ ] 모달 창 수정 된 정보 체크리스트 윗 부분 뷰에 뿌리기 (?)
- [ ] 체크리스트 윗 부분 정보 수정 : 사진 & 별점 & 세부 평가 PATCH

**Comment by Yeonseo-Jo** [comment]
현지가 작업한 뷰에 api 붙이기 위해 동일 내용 새 이슈로 재등록 후 새 브랜치에서 작업합니다
